# These are supported funding model platforms

github: [devansh07mehta]  # Your GitHub Sponsors-enabled username
patreon: DevanshMehta                # Replace with your Patreon username
open_collective: DevanshMehta        # Replace with your Open Collective username
ko_fi: DevanshMehta                  # Replace with your Ko-fi username
tidelift: npm/book-my-show           # Replace with a package you're maintaining
community_bridge: cloud-foundry      # Replace with your Community Bridge project name
liberapay: DevanshMehta              # Replace with your Liberapay username
issuehunt: DevanshMehta              # Replace with your IssueHunt username
lfx_crowdfunding: cloud-foundry      # Replace with your LFX Crowdfunding project name
polar: DevanshMehta                  # Replace with your Polar username
buy_me_a_coffee: DevanshMehta        # Replace with your Buy Me a Coffee username
thanks_dev: DevanshMehta             # Replace with your thanks.dev username
custom: ['https://devanshmehta.com/donate', 'https://anothercustomlink.com'] # Replace with custom URLs

